### ISSUE TITLE
Unable to install `@tand_ferret/useful_hooks@0.0.1`

### ISSUE THREAD

**Issue by Konard** [deep-foundation/npm-packager#100]
![image](https://github.com/deep-foundation/npm-packager/assets/1431904/d4cb3a3e-8c11-43c4-b1b0-792fbab03bb1)

```json
{
  "errors": [
    {}
  ]
}
```

[js-docker-isolation-provider.log.txt](https://github.com/deep-foundation/npm-packager/files/14628831/js-docker-isolation-provider.log.txt)

**Comment by Konard** [comment]
First, https://github.com/deep-foundation/js-docker-isolation-provider/issues/7 and https://github.com/deep-foundation/npm-packager/issues/53 should be fixed.

**Comment by Konard** [comment]
Now error looks like this:
![Screenshot_20240323_041749](https://github.com/deep-foundation/npm-packager/assets/1431904/84bece3d-b96f-4110-b49d-f4e2c68a4d84)
```json
{
  "errors": [
    {
      "name": "Error",
      "cause": {
        "name": "ApolloError",
        "stack": "ApolloError: Undefined symbol x\n    at new ApolloError (/node_modules/@apollo/client/errors/errors.cjs:33:28)\n    at /node_modules/@apollo/client/core/core.cjs:1427:47\n    at both (/node_modules/@apollo/client/utilities/utilities.cjs:1269:31)\n    at /node_modules/@apollo/client/utilities/utilities.cjs:1260:72\n    at new Promise (<anonymous>)\n    at Object.then (/node_modules/@apollo/client/utilities/utilities.cjs:1260:24)\n    at Object.next (/node_modules/@apollo/client/utilities/utilities.cjs:1271:49)\n    at notifySubscription (/node_modules/zen-observable/lib/Observable.js:135:18)\n    at onNotify (/node_modules/zen-observable/lib/Observable.js:179:3)\n    at SubscriptionObserver.next (/node_modules/zen-observable/lib/Observable.js:235:7)",
        "message": "Undefined symbol x",
        "clientErrors": [],
        "networkError": null,
        "graphQLErrors": [
          {
            "message": "database query error",
            "extensions": {
              "code": "unexpected",
              "path": "$.selectionSet.insert_strings.args.objects",
              "internal": {
                "error": {
                  "hint": null,
                  "message": "Undefined symbol x",
                  "description": null,
                  "exec_status": "FatalError",
                  "status_code": "XX000"
                },
                "prepared": false,
                "arguments": [],
                "statement": "WITH \"strings__mutation_result_alias\" AS (INSERT INTO \"public\".\"strings\" ( \"link_id\", \"value\", \"id\" ) VALUES (('1202')::bigint, ('5 * (x * 0.25)')::text, DEFAULT)  RETURNING * , ('true')::boolean AS \"check__constraint\"), \"strings__all_columns_alias\" AS (SELECT  \"id\" , \"link_id\" , \"value\"  FROM \"strings__mutation_result_alias\"      ) SELECT  json_build_object('returning', (SELECT  coalesce(json_agg(\"root\" ), '[]' ) AS \"root\" FROM  (SELECT  row_to_json((SELECT  \"_1_e\"  FROM  (SELECT  \"_0_root.base\".\"id\" AS \"id\", 'strings' AS \"__typename\"       ) AS \"_1_e\"      ) ) AS \"root\" FROM  (SELECT  *  FROM \"strings__all_columns_alias\" WHERE ('true')     ) AS \"_0_root.base\"      ) AS \"_2_root\"      ), '__typename', 'strings_mutation_response' ) , (SELECT  coalesce(bool_and(\"check__constraint\" ), 'true' )  FROM \"strings__mutation_result_alias\"      )        "
              }
            }
          }
        ],
        "protocolErrors": []
      },
      "stack": "Error: DeepClient Serial Error: Undefined symbol x\n    at DeepClient.<anonymous> (file:///node_modules/@deep-foundation/deeplinks/imports/client.js:593:27)\n    at Generator.throw (<anonymous>)\n    at rejected (file:///node_modules/@deep-foundation/deeplinks/imports/client.js:5:65)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)",
      "message": "DeepClient Serial Error: Undefined symbol x"
    }
  ]
}
```
