### ISSUE TITLE
{   "errors": [     {}   ] }

### ISSUE THREAD

**Issue by flakeed** [deep-foundation/npm-packager#53]
After trying to install the package I get the following error:
```
{
  "errors": [
    {}
  ]
}
```
but in the console I have another error:
```
 errors: [
    ApolloError: Type conflict link: { id: 1009, type: 49, from: 1008, to: 1010 } expected type: { type: 49, from: 8, to: 35 } received type: { type: 49, from: 1, to: 0 }
        at new ApolloError (/node_modules/@apollo/client/errors/errors.cjs:34:28)
        at /node_modules/@apollo/client/core/core.cjs:1289:47
        at both (/node_modules/@apollo/client/utilities/utilities.cjs:997:53)
        at /node_modules/@apollo/client/utilities/utilities.cjs:990:72
        at new Promise (<anonymous>)
        at Object.then (/node_modules/@apollo/client/utilities/utilities.cjs:990:24)
        at Object.next (/node_modules/@apollo/client/utilities/utilities.cjs:998:49)
        at notifySubscription (/node_modules/zen-observable/lib/Observable.js:135:18)
        at onNotify (/node_modules/zen-observable/lib/Observable.js:179:3)
        at SubscriptionObserver.next (/node_modules/zen-observable/lib/Observable.js:235:7) {
      graphQLErrors: [Array],
      clientErrors: [],
      networkError: null,
      extraInfo: undefined
    }
  ]
}
rejected { errors: [ {} ] }
```

**Comment by FreePhoenix888** [comment]
Copy of https://github.com/deep-foundation/js-docker-isolation-provider/issues/7 ?
