### ISSUE TITLE
`Cannot read properties of undefined (reading 'filter')` on package save

### ISSUE THREAD

**Issue by Konard** [deep-foundation/npm-packager#67]
![image](https://github.com/deep-foundation/npm-packager/assets/1431904/d58fe3ab-b3e4-4096-9499-e5f955824949)

```
VM216:79 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'filter')
    at eval (eval at <anonymous> (4294-411eddb750d032e1.js:310:67016), <anonymous>:79:99)
    at Generator.next (<anonymous>)
    at fulfilled (eval at <anonymous> (4294-411eddb750d032e1.js:310:67016), <anonymous>:4:58)
```

**Comment by Konard** [comment]
# Workaround

These links can be created manually

![Screenshot_20230928_201551](https://github.com/deep-foundation/npm-packager/assets/1431904/7b278f73-aa72-4dd4-9744-4d722dfb2ef3)

**Comment by Konard** [comment]
When all links are created, and all values are set, it is possible to update them using `save` button in `packageClientHandler`.

![Screenshot_20230928_203717](https://github.com/deep-foundation/npm-packager/assets/1431904/973154ca-ee06-4494-81db-11dd7d817cff)
