### ISSUE TITLE
Failed install package with dependenies

### ISSUE THREAD

**Issue by suenot** [deep-foundation/npm-packager#80]
### Describe the bug

It happend in clear deepcase in production. It hapened once and I can't repeat it new instance of deep in gitpod.

### Current Behavior

Js docker isolation log: https://gist.githubusercontent.com/suenot/db4c7c16be9459660497d5702a5d38e1/raw/6013776f4d9f1abdc908bdea8bfb15b903e7f083/gistfile1.txt

### Steps to reproduce

- I click install package '@suenot/transaction-tests'. Maybe I clicked two times fast (because click on touchpad hard to control).
- Get error:
```
{
  "stack": "Error: Multiple packages with name '@suenot/wallet' exist.\n    at eval (eval at memoized (/node_modules/lodash/memoize.js:62:23), <anonymous>:176:17)\n    at Array.reduce (<anonymous>)\n    at getExistingPackages (eval at memoized (/node_modules/lodash/memoize.js:62:23), <anonymous>:168:39)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async eval (eval at memoized (/node_modules/lodash/memoize.js:62:23), <anonymous>:234:28)",
  "message": "Multiple packages with name '@suenot/wallet' exist."
}
```

### Environment

```shell
deepcase 0.1.0-beta.12 (0.0.98)
```

**Comment by suenot** [comment]
Проблема до сих порт актуальна.
Возникает если ставлю пакет  '@suenot/unit' и  '@suenot/wallet', а потом '@suenot/payment-tests', который использует эти пакеты. При установке  '@suenot/payment-tests' ставятся еще пакеты, которые не законтейнены на пользователя, но сам процесс установки с ошибкой, так как мешают уже установленные пакеты. Если удалить  '@suenot/unit' и  '@suenot/wallet' и повторить установку  '@suenot/payment-tests', то будут ошибки, что пакеты-зависимости существуют и получаем ошибку. Что-то как-то это решить походу надо выводить список все установленных пакетов и удалять то, что было поставлено пакетным менеджером при попытке установить  '@suenot/payment-tests'.

**Comment by konard** [comment]
@suenot какой самый простой способ это воспроизвести? Установки `@suenot/transaction-tests` достаточно?
