### ISSUE TITLE
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@tand_ferret%2fuseful_hooks - Not found

### ISSUE THREAD

**Issue by Konard** [deep-foundation/npm-packager#97]
```
{
  "pid": 139,
  "stack": "Error: Command failed: npm --prefix \"/tmp/50de4cc8-bac5-478e-ac52-9763c34ef579\" i @tand_ferret/useful_hooks@0.0.1\nnpm ERR! code E404\nnpm ERR! 404 Not Found - GET https://registry.npmjs.org/@tand_ferret%2fuseful_hooks - Not found\nnpm ERR! 404 \nnpm ERR! 404  '@tand_ferret/useful_hooks@0.0.1' is not in this registry.\nnpm ERR! 404 \nnpm ERR! 404 Note that you can also install from a\nnpm ERR! 404 tarball, folder, http url, or git url.\n\nnpm ERR! A complete log of this run can be found in: /root/.npm/_logs/2024-03-15T00_36_30_552Z-debug-0.log\n\n    at checkExecSyncError (node:child_process:890:11)\n    at execSync (node:child_process:962:15)\n    at npmInstall (eval at memoized (/node_modules/lodash/memoize.js:62:23), <anonymous>:20:20)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async eval (eval at memoized (/node_modules/lodash/memoize.js:62:23), <anonymous>:219:5)",
  "output": [
    null,
    "",
    "npm ERR! code E404\nnpm ERR! 404 Not Found - GET https://registry.npmjs.org/@tand_ferret%2fuseful_hooks - Not found\nnpm ERR! 404 \nnpm ERR! 404  '@tand_ferret/useful_hooks@0.0.1' is not in this registry.\nnpm ERR! 404 \nnpm ERR! 404 Note that you can also install from a\nnpm ERR! 404 tarball, folder, http url, or git url.\n\nnpm ERR! A complete log of this run can be found in: /root/.npm/_logs/2024-03-15T00_36_30_552Z-debug-0.log\n"
  ],
  "signal": null,
  "status": 1,
  "stderr": "npm ERR! code E404\nnpm ERR! 404 Not Found - GET https://registry.npmjs.org/@tand_ferret%2fuseful_hooks - Not found\nnpm ERR! 404 \nnpm ERR! 404  '@tand_ferret/useful_hooks@0.0.1' is not in this registry.\nnpm ERR! 404 \nnpm ERR! 404 Note that you can also install from a\nnpm ERR! 404 tarball, folder, http url, or git url.\n\nnpm ERR! A complete log of this run can be found in: /root/.npm/_logs/2024-03-15T00_36_30_552Z-debug-0.log\n",
  "stdout": "",
  "message": "Command failed: npm --prefix \"/tmp/50de4cc8-bac5-478e-ac52-9763c34ef579\" i @tand_ferret/useful_hooks@0.0.1\nnpm ERR! code E404\nnpm ERR! 404 Not Found - GET https://registry.npmjs.org/@tand_ferret%2fuseful_hooks - Not found\nnpm ERR! 404 \nnpm ERR! 404  '@tand_ferret/useful_hooks@0.0.1' is not in this registry.\nnpm ERR! 404 \nnpm ERR! 404 Note that you can also install from a\nnpm ERR! 404 tarball, folder, http url, or git url.\n\nnpm ERR! A complete log of this run can be found in: /root/.npm/_logs/2024-03-15T00_36_30_552Z-debug-0.log\n"
}
```

**Comment by Konard** [comment]
# Workaround 1

Wait 10 minutes and install the package again.

**Comment by Konard** [comment]
Check if there are duplicates of this issue before close.

**Comment by Konard** [comment]
No other duplicates found. Looks like this is a problem on NPM side: https://github.com/npm/cli/issues/6644 (this issue closed, but it continues to reproduce, comment to the issue is added).

Closing as workaround may be considered a solution for now. But it would be nice if it is solved on NPM side also.
